---

- apt_repository:
    repo: ppa:openjdk-r/ppa
  become: true

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day
  become: true

- name: install JDK 11
  apt:
    name: openjdk-11-jdk
    state: present
  become: true

- name: add tomcat group
  group:
    name: tomcat
  become: true

- name: add tomcat user
  user:
    name: tomcat
    group: tomcat
    home: /user/share/tomcat
    createhome: no
  become: true

- name: create /opt/tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    mode: 0755
  become: true

- name: download & unarchive
  unarchive:
    src: http://apache.proserve.nl/tomcat/tomcat-9/v9.0.22/bin/apache-tomcat-9.0.22.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: true

- name: Change ownership
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory
  become: true

- name: Copy Tomcat service from local to remote
  copy:
    src: files/tomcat.service
    dest: /etc/systemd/system/
    mode: 0755
  become: true

- name: Start and enable Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: true
    daemon_reload: true
  become: true